SELECT DELIVERERID
FROM DELIVERERS
WHERE DELIVERERID IN (SELECT P1.DELIVERERID
                        FROM  PENALTIES P1, PENALTIES P2
                        WHERE P1.DELIVERERID=P2.DELIVERERID AND P1.AMOUNT=25 
                        AND P2.AMOUNT=30)