SELECT DELIVERERID, NAME
FROM DELIVERERS
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM PENALTIES
                        GROUP BY DELIVERERID, DATA
                        HAVING COUNT(*)>1)