SELECT P1.DELIVERERID
FROM (SELECT COUNT(*) SM,DELIVERERID
        FROM PENALTIES
        WHERE DATA>=TO_DATE('01/01/1980','DD/MM/YYYY') AND 
            DATA<=TO_DATE('31/12/1980','DD/MM/YYYY')
        GROUP BY DELIVERERID) P1, 
        (SELECT COUNT(*) SM,DELIVERERID
        FROM PENALTIES
        WHERE DATA>=TO_DATE('01/01/1981','DD/MM/YYYY') AND 
            DATA<=TO_DATE('31/12/1981','DD/MM/YYYY')
        GROUP BY DELIVERERID) P2
WHERE P1.SM>P2.SM AND P1.DELIVERERID=P2.DELIVERERID;

/* NON FUNZIONA */