SELECT DELIVERERID
FROM COMPANYDEL
WHERE DELIVERERID<>'57' AND COMPANYID IN 
    (SELECT C2.COMPANYID
        FROM COMPANYDEL C2
        WHERE C2.DELIVERERID='57')
GROUP BY DELIVERERID 
HAVING COUNT(*)= (SELECT COUNT(*)
                    FROM COMPANYDEL
                    WHERE DELIVERERID='57')