 SELECT A.CODAUTORE,COGNOME,UNIVERSITA,COUNT(*)
 FROM AUTORE A,AUTORE-PRESENTA-ARTICOLO APA
 WHERE APA.CODAUTORE=A.CODAUTORE
        AND CODAUTORE
        NOT IN (SELECT CODAUTORE
                FROM AUTORE-PRESENTA-ARTICOLO APA2, ARTICOLO AR
                WHERE APA2.CODARTICOLO=AR.CODARTICOLO AND
                AR.ARGOMENTO<>'DATAMINING')
GROUP BY A.CODAUTORE,CONFERENZA,EDIZIONE,COGNOME,UNIVERSITA
 
