SELECT MATRDOC,CODCORSO
FROM LEZIONE L,CORSO C
WHERE L.CODCORSO=C.CODCORSO AND
      MATRDOC NOT IN (SELECT MATRDOC
                      FROM CORSO C2
                      WHERE AREA<>'BASI DI DATI')
GROUP BY MATRDOC,CODCORSO
HAVING AVG(CORSO.NUMEROSTUDENTIPRESENTI)=(SELECT MAX(AVERAGE)
                                          FROM (SELECT CODCORSO,AVG(NUMEROSTUDENTIISCRITTI) AS AVERAGE
                                                  FROM LEZIONE
                                                  GROUP BY CODCORSO)) AS TFMEDIA,CORSO CO
                                          WHERE TFMEDIA.COD CORSO=CO.CODCORSO AND C.MATRCOD=CO.MATRCOD
