SELECT C.Nome, C.Cognome, S.NomeS
FROM CICLISTA C, SQUADRA S
WHERE C.CodC=0022 AND S.CodS=C.CodS



SELECT Edizione, Posizione
FROM CLASSIFICA_INDIVIDUALE
WHERE CodC=0022 AND CodT=100
ORDER BY Edizione
