SELECT D.NAME,D.INITIALS
FROM DELIVERERS D
WHERE D.DELIVERERID IN (SELECT P.DELIVERERID
                        FROM PENALTIES P
                        WHERE P.DATA>TO_DATE('31/12/1980','DD/MM/YYYY'))
        AND D.DELIVERERID IN (SELECT C.DELIVERERID
                                FROM COMPANIES C)
ORDER BY NAME
