/*CORSO (CodCorso, NomeC, Anno, Semestre)
 *ORARIO-LEZIONI (CodCorso,GiornoSettimana,OraInizio,OraFine,Aula)
 */
 
/* TROVARE CODICE CORSO, NOME CORSO E NUMERO TOTALE DI ORE
 *DI LEZIONE SETTIMANALI PER I CORSI DEL TERZO ANNO PER CUI
 *IL NUMERO COMPLESSIVO DI ORE DI LEZIONI SETTIMANALI E' 
 *SUPERIORE A 10 E LE LEZIONI SONO IN PIU' DI 3 GIORNI DIVERSI
 *A SETTIMANA
*/

SELECT C.CodCorso, C.NomeC, SUM(ORAFINE-ORAINIZIO)
FROM CORSO C, ORARIO-LEZIONI OL
WHERE C.CodCorso=OL.CodCorso AND Anno=3
GROUP BY C.CodCorso, C.NomeC,  /*<-- devo mettere tutti gli attributi che metto
								*nella select 
								*/
HAVING SUM(ORAFINE-ORAINIZIO)>10 COUNT(DISTINCT GiornoSettimana)>3