/*ALLOGIO (CodA,Indirizzo,Città,Superficie,CostoAffittoMensile)
 *CONTRATTO-AFFITTO(CodC,DataInizio,DataFine,NomePersona,CodA)
*/

/* TROVARE, PER LE CITTA' IN CUI SONO STATI STIPULATI ALMENO 100
 *CONTRATTI, LA CITTA' ,IL COSTO MENSILE MASSIMO DEGLI AFFITTI, IL COSTO 
 *MENSILE MEDIO DEGLI AFFITTI, LA DURATA MASSIMA DEI CONTRATTI, LA DURATA
 *MEDIA DEI CONTRATTI E IL NUMERO TOTALE DEI CONTRATTI STIPULATI
*/

SELECT A.Città, MAX(CostoAffittoMensile), AVG(CostoAffittoMensile), MAX(DataFine-DataInizio),
		AVG(DataFine-DataInizio), COUNT(*)
FROM ALLOGIO A, CONTRATTO-AFFITTO CA
WHERE A.codA=CA.CodA
GROUP BY A.Città
HAVING COUNT(*)>=100