CREATE OR REPLACE TRIGGER AGGIORNA_DIP
AFTER UPDATE ON DNAME ON DIP
FOR EACH ROW
WHEN(OLD.DNAME='ACCOUNTING' AND NEW.DNAME='SALES')
BEGIN
    UPDATE IMP
    SET SAL=SAL+100
    WHERE DEPTNO=:OLD.DEPTNO;
END;
/
